### ISSUE TITLE
Polls not working

### ISSUE THREAD

**Issue by Gillingham** [matnad/pollmaster#44]
When the bot tries to post a poll get the following stacktrace, on commit f66a05156739660d54a461cec989bb229bab8a83

Looks like this is a bug upstream and was fixed in https://github.com/Rapptz/discord.py/issues/2422
Upgrading to `discord.py==1.2.3` in requirements.txt resolves it for me.

```
1|pollmaster  | Unclosed client session
1|pollmaster  | client_session: <aiohttp.client.ClientSession object at 0x7fdfc5317390>
1|pollmaster  | Traceback (most recent call last):
1|pollmaster  |   File "pollmaster/pollmaster.py", line 145, in <module>
1|pollmaster  |     bot.run(SETTINGS.bot_token)
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/client.py", line 598, in run
1|pollmaster  |     return future.result()
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/client.py", line 579, in runner
1|pollmaster  |     await self.start(*args, **kwargs)
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/client.py", line 543, in start
1|pollmaster  |     await self.connect(reconnect=reconnect)
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/client.py", line 457, in connect
1|pollmaster  |     await self._connect()
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/shard.py", line 274, in _connect
1|pollmaster  |     f.result()
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/shard.py", line 78, in poll
1|pollmaster  |     await self.ws.poll_event()
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/gateway.py", line 469, in poll_event
1|pollmaster  |     await self.received_message(msg)
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/gateway.py", line 423, in received_message
1|pollmaster  |     func(data)
1|pollmaster  |   File ".pyenv/versions/3.7.4/lib/python3.7/site-packages/discord/state.py", line 407, in parse_message_reaction_add
1|pollmaster  |     emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
1|pollmaster  | KeyError: 'animated'
1|pollmaster  | Unclosed client session
1|pollmaster  | client_session: <aiohttp.client.ClientSession object at 0x7fdfc4279850>
```

```
$ pip freeze
aiohttp==3.5.4
async-timeout==3.0.1
asyncpg==0.18.3
attrs==19.1.0
bson==0.5.8
chardet==3.0.4
cycler==0.10.0
dateparser==0.7.1
dblpy==0.3.2
discord.py==1.2.3
idna==2.8
idna-ssl==1.1.0
kiwisolver==1.0.1
matplotlib==3.0.3
motor==2.0.0
multidict==4.5.2
numpy==1.17.1
pymongo==3.9.0
pyparsing==2.4.2
python-dateutil==2.8.0
pytz==2019.2
ratelimiter==1.2.0.post0
regex==2019.8.19
six==1.12.0
typing-extensions==3.7.2
tzlocal==1.5.1
Unidecode==1.1.1
websockets==6.0
yarl==1.3.0
```

**Comment by matnad** [comment]
thanks
